server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///hm49
    username: root
    password: root
  rabbitmq:
    host: 192.168.11.128
    virtual-host: leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo